version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-deploy
    env_file:
      - .env
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    working_dir: /app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx
    networks:
      - app-network
    command: certonly --webroot --webroot-path=/var/www/certbot --email al6ity@gmail.com --agree-tos --no-eff-email -d mcsad.sytes.net --dry-run

networks:
  app-network:
    driver: bridge