services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - .:/data
    restart: unless-stopped
