// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/server/deploy": {
            "post": {
                "description": "Deploys the Minecraft server web application on the target server via SSH",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Deploy Minecraft server",
                "parameters": [
                    {
                        "description": "SSH connection details",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeploymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DeploymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.DeploymentRequest": {
            "type": "object",
            "required": [
                "password",
                "server_ip",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "securepassword"
                },
                "server_ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "v1.DeploymentResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Deployment completed successfully"
                },
                "output": {
                    "type": "string",
                    "example": "$ sudo pacman -Syu..."
                }
            }
        },
        "v1.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "dial tcp 192.168.1.100:22: connect: connection refused"
                },
                "error": {
                    "type": "string",
                    "example": "SSH connection failed"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
