// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/minecraft/current": {
            "get": {
                "description": "Returns currently selected server type and version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minecraft"
                ],
                "summary": "Get current server configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/minecraft.ServerInfo"
                        }
                    }
                }
            }
        },
        "/api/v1/minecraft/select": {
            "post": {
                "description": "Saves selected Minecraft version and server type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minecraft"
                ],
                "summary": "Select Minecraft version and core",
                "parameters": [
                    {
                        "description": "Selection data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/minecraft.VersionSelectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/minecraft/versions": {
            "get": {
                "description": "Returns list of available Minecraft versions and server cores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minecraft"
                ],
                "summary": "Get available Minecraft versions and cores",
                "responses": {
                    "200": {
                        "description": "Returns versions and cores",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/server/restart": {
            "post": {
                "description": "Перезагружает сервер Minecraft через docker-compose",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minecraft"
                ],
                "summary": "Перезагрузка сервера Minecraft",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/server/start": {
            "post": {
                "description": "Запускает сервер Minecraft через docker-compose",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minecraft"
                ],
                "summary": "Запуск сервера Minecraft",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/server/stop": {
            "post": {
                "description": "Останавливает сервер Minecraft через docker-compose",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minecraft"
                ],
                "summary": "Остановка сервера Minecraft",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "minecraft.ServerInfo": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "minecraft.VersionSelectionRequest": {
            "type": "object",
            "required": [
                "core_option",
                "core_type",
                "version"
            ],
            "properties": {
                "core_option": {
                    "type": "string"
                },
                "core_type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
