info:
  contact: {}
paths:
  /api/v1/server/start:
    post:
      description: Запускает сервер Minecraft через docker-compose
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Запуск сервера Minecraft
      tags:
      - minecraft
swagger: "2.0"
