services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-webapp
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    working_dir: /app